### ISSUE TITLE
页面不存在

### ISSUE THREAD

**Issue by kingyueyang** [imarvinle/awesome-cs-books#3]
您好，非常感谢您整理、分享的知识，不过在我打开百度网盘链接时提示：
啊哦，你所访问的页面不存在了。
链接地址 https://pan.baidu.com/s/1PERa4bL7K-FoXit5440YNQ

**Comment by imarvinle** [comment]
可以的, 建议你换浏览器试试, 我刚才开匿名页面测试过了.
